### ISSUE TITLE
Possible bug with hidden fields and cakephp 3.7.3

### ISSUE THREAD

**Issue by tecnopolis-ve** [lilHermit/cakephp-plugins-bootstrap4#10]
I've found an error with Cakephp 3.7.3 and this plugin (v. 4002)

![image](https://user-images.githubusercontent.com/18125217/52002024-2afca800-24c1-11e9-8134-2f018cba2b04.png)

I've figured out how to "fix" it doing the follow:

in FormHelper.php, line 180 `public function control($fieldName, array $options = []) {`

Yo have to edit the following block

>         $options += [
>            'customControls' => $this->getConfig('customControls'),
>            'html5Render' => $this->getConfig('html5Render'),
>            'help' => false,
>            'prepend' => false,
>            'append' => false,
>            'gridClasses' => $this->getConfig('layout.classes.grid')
>        ];

Add `'required' => false`

>         $options += [
>            'customControls' => $this->getConfig('customControls'),
>            'html5Render' => $this->getConfig('html5Render'),
>            'help' => false,
>            'prepend' => false,
>            'append' => false,
>            'required'  => $this->getConfig('required'),
>            'gridClasses' => $this->getConfig('layout.classes.grid')
>        ];

https://github.com/cakephp/cakephp/issues/12887

**Comment by lilHermit** [comment]
Can you confirm this is now fixed for you in dev-master?

**Comment by lilHermit** [comment]
This is fix is now live
