### ISSUE TITLE
bootstrapCss/Script does not exist

### ISSUE THREAD

**Issue by Mark-81** [lilHermit/cakephp-plugins-bootstrap4#13]
With CakePHP 3.7.7 I followed the instruction [here](https://projects.lilhermit.co.uk/cakephp-plugins-bootstrap4/installation.html) and [here](https://projects.lilhermit.co.uk/cakephp-plugins-bootstrap4/helpers/html.html), but when the page loads it says:

>Warning (512): Method Cake\View\Helper\HtmlHelper::bootstrapCss does not exist [CORE/src/View/Helper.php, line 117]
>Warning (512): Method Cake\View\Helper\HtmlHelper::bootstrapScript does not exist [CORE/src/View/Helper.php, line 117]
>Warning (512): Method Cake\View\Helper\HtmlHelper::button does not exist [CORE/src/View/Helper.php, line 117]

Is there something else I have to do?

**Comment by lilHermit** [comment]
Hi thanks for posting an issue can you provide a working/failing project to a repo somewhere so I can see?

**Comment by lilHermit** [comment]
This looks like you are extending `BootstrapView`

**Comment by lilHermit** [comment]
Stale
