### ISSUE TITLE
cant bake with dev-master version

### ISSUE THREAD

**Issue by johnneijzen** [lilHermit/cakephp-plugins-bootstrap4#14]
Wrote `/home/johnneijzen/Documents/whereabouts/src/Template/Locations/add.ctp`
PHP Fatal error:  Cannot redeclare getColumn() (previously declared in /home/johnneijzen/Documents/whereabouts/tmp/bake/Bake-Element-form-ctp.php:32) in /home/johnneijzen/Documents/whereabouts/tmp/bake/Bake-Element-form-ctp.php on line 39
<CakePHPBakeOpenTagphp
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Location $location
 */

$this->set('bakeEntities', array (
  0 => 'Locations',
  1 => 'Rooms',
  2 => 'Buildings',
  3 => 'Areas',
  4 => 'Tasks',
));
CakePHPBakeCloseTag>

Fatal error: Cannot redeclare getColumn() (previously declared in /home/johnneijzen/Documents/whereabouts/tmp/bake/Bake-Element-form-ctp.php:32) in /home/johnneijzen/Documents/whereabouts/tmp/bake/Bake-Element-form-ctp.php on line 39

**Comment by lilHermit** [comment]
Hi thanks for the bug report.

I have pushed a fix to `master`, could you please confirm this fixes your issue?

Many thanks

**Comment by johnneijzen** [comment]
i will test tomorrow sorry i don't have pc with CakePHP on it

**Comment by johnneijzen** [comment]
@lilHermit Confirmed Fixed so far I can see.
