### ISSUE TITLE
Use of depreciated methods and depreciated parameter access

### ISSUE THREAD

**Issue by Ali1** [lilHermit/cakephp-plugins-bootstrap4#17]
Just to start the conversation about this - noticed a few `/** @noinspection PhpDeprecationInspection */`

To prepare for CakePHP 4

**Comment by lilHermit** [comment]
If you want to create a branch locally and create a PR we can get the ball rolling

**Comment by Ali1** [comment]
Hadn't looked close enough, all the depreciated methods were when newer methods did not exist and were left for backwards compatibility.

So all good I think.

**Comment by lilHermit** [comment]
Cakephp 4 support is now in master, will do a release as soon as possible
