### ISSUE TITLE
custom file form input

### ISSUE THREAD

**Issue by wilsmex** [lilHermit/cakephp-plugins-bootstrap4#7]
Via https://projects.lilhermit.co.uk/cakephp-plugins-bootstrap4/helpers/form.html#creating-custom-file-browser

when I select a file via the 'custom file input' option, the filename doesn't show and it looks like no file was selected (but it does in fact work)

**Comment by lilHermit** [comment]
Hi are you using the plugin to get css/js markup or are you including yourself. If including yourself make sure the js matches the latest BS the plugin supports. 

Do you have a url where this behaviour can be seen?

**Comment by wilsmex** [comment]
I'm including the css/js myself.  I think I may be including BS 4.1, which may be the issue, however I'm seeing that same issue on your same page I linked above (which looks like it is including the correct BS css/js to match the plugin)?

**Comment by lilHermit** [comment]
Looking at the BS 4 documentation, that doesn't show any signs of file selecting either

https://getbootstrap.com/docs/4.0/components/forms/#file-browser

**Comment by wilsmex** [comment]
I see, after some digging, it seems that part is yet to be implemented properly.  I ended up using jquery to grab and swap the values out, which works fine for me.
