### ISSUE TITLE
Add new "confirmJS" template to templates array

### ISSUE THREAD

**Issue by wilsmex** [lilHermit/cakephp-plugins-bootstrap4#8]
Cake 3.6 and above has a new confirmJS template which needs to be added to the plugin's templates

`'confirmJs' => '{{confirm}}',`

**Comment by johnneijzen** [comment]
how can fix this my cakephp because your "bin/cake bake template -t LilHermit/Bootstrap4 Users" will give me Cannot find template named 'confirmJs'.

**Comment by lilHermit** [comment]
You can switch to the master branch by using `dev:master` instead of a version number, I'll be pushing the latest version as soon as I have time.

Note: You may need to add `"minimum-stability": "dev"` to your composer.json

**Comment by tgoeminne** [comment]
Do we need to change existing templates? Because I am getting the same error. CofirmJs

**Comment by tgoeminne** [comment]
Ok nevermind, I updated to latest version all seems to work now, somehow it didn't update correctly earlier... Thanks
